version: '3'
services:
  shop.backend:
    image: ghcr.io/gorinovv/shop_backend/shop_backend:develop
    container_name: shop_backend
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./.env:/opt/app/.env
